# Generated by Django 4.1.7 on 2023-06-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="status",
            field=models.CharField(
                choices=[("C", "Completed"), ("F", "Pending")], max_length=50
            ),
        ),
    ]
