# Generated by Django 4.2.2 on 2023-06-13 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="data",
            options={"verbose_name": "Data1"},
        ),
    ]
