# Generated by Django 4.2.2 on 2023-06-13 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="choice",
            options={"verbose_name_plural": "Choice"},
        ),
        migrations.AlterModelOptions(
            name="question",
            options={"verbose_name_plural": "Question"},
        ),
        migrations.RenameField(
            model_name="choice",
            old_name="choise_text",
            new_name="choice_text",
        ),
    ]
