# Generated by Django 4.2.2 on 2023-06-14 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0002_alter_choice_options_alter_question_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="pub_text",
            field=models.DateTimeField(null=True, verbose_name="date published"),
        ),
    ]
