# Generated by Django 4.1.7 on 2023-06-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0002_remove_photo_discription_photo_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photo",
            name="description",
        ),
        migrations.AddField(
            model_name="photo",
            name="discription",
            field=models.TextField(null=True),
        ),
    ]
