# Generated by Django 4.1.7 on 2023-03-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="service_des",
            field=models.TextField(
                blank=True, default="DEFAULT VALUE", max_length=60, null=True
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="service_icon",
            field=models.CharField(default="DEFAULT VALUE", max_length=60),
        ),
        migrations.AddField(
            model_name="service",
            name="service_title",
            field=models.CharField(default="DEFAULT VALUE", max_length=50),
        ),
    ]
