# Generated by Django 4.1.7 on 2023-05-24 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0002_rename_emp_id_employee_empid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="empid",
        ),
    ]
