# Generated by Django 4.1.7 on 2023-05-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0003_remove_employee_empid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="is_head",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
